### PR TITLE
bumped Versions of geckoEMF and EMF

### PR DESCRIPTION
**Pull request by juergen-albert**

### CODE REVIEW

**Comment by timothyjward** [comment]
@juergen-albert - I've sorted Dash, the rest is down to you I'm afraid!

**Comment by juergen-albert** [comment]
Thanks heaps. I found an issue though, which would have forced metatype upon us and I needed to do a new geckEMF release first.

**Comment by timothyjward** [comment]
> Thanks heaps. I found an issue though, which would have forced metatype upon us and I needed to do a new geckEMF release first.

Let me know when the PR is ready and I can poke Dash again.

**Comment by juergen-albert** [comment]
Thanks for the Hand, but I already did it.

**Pull request merged**
